apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upload-source-artefact.yaml
  - create-blank-root-disk.yaml
  - wait-for-vm-shutdown.yaml
  - clone-to-catalog.yaml
  - cleanup-build-namespace.yaml
