apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora41-validation
  namespace: vm-golden-images
spec:
  runStrategy: Always
  instancetype:
    kind: VirtualMachineInstancetype
    name: fedora-small
    inferFromVolume: false
  preference:
    kind: VirtualMachinePreference
    name: fedora41-golden
    inferFromVolume: false
  template:
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: fedora41-base-v1
