apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - build-namespaces
  - shared-tasks/overlays/linux
  - shared-tasks/overlays/windows
  - boot-trigger-tasks/overlays/linux
  - boot-trigger-tasks/overlays/windows
